version: '3.1'

services:
  db:
    container_name: payment_postgres
    image: postgres:13.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./db-postgres/db:/var/lib/postgresql/data
      - ./db-postgres/import:/import
    networks:
      - docker-compose

  #  adminer:
  #    image: adminer
  #    restart: always
  #    ports:
  #      - 8090:8080

  # https://github.com/khezen/compose-postgres/blob/master/docker-compose.yml
  pgadmin:
    container_name: payment_pgadmin
    image: dpage/pgadmin4:5.5
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./db-postgres/pgadmin:/root/.pgadmin
    ports:
      - "8090:80"
    networks:
      - docker-compose
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=passme
      - DB_VENDOR=h2
    ports:
      - '8180:8080'
    image: 'quay.io/keycloak/keycloak:15.0.2'
    networks:
      - docker-compose

networks:
  docker-compose:
    driver: bridge