apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: student-o-sugic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/htl-leonding-project/2022-da-excursion-guide-frontend:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: student-o-sugic
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: frontend