
    create table Activity (
       id int8 generated by default as identity,
        activityName varchar(255),
        comment varchar(255),
        isPublic boolean not null,
        latitude float8 not null,
        longitude float8 not null,
        publicationDate date,
        startDateTime timestamp,
        previousActivity_id int8,
        topic_id int8,
        primary key (id)
    );

    create table Event (
       id int8 generated by default as identity,
        maxPersonAllowed int4 not null,
        name varchar(255),
        planedEndDateTime timestamp,
        planedStartDateTime timestamp,
        type varchar(255),
        primary key (id)
    );

    create table Person (
       id int8 generated by default as identity,
        comment varchar(255),
        firstname varchar(255),
        lastname varchar(255),
        role int4,
        telephone varchar(255),
        event_id int8,
        primary key (id)
    );

    create table Topic (
       id int8 generated by default as identity,
        comment varchar(255),
        name varchar(255),
        event_id int8,
        previousTopic_id int8,
        primary key (id)
    );

    alter table if exists Activity 
       add constraint FK3lxim153ss7jq1leyw97fn32i 
       foreign key (previousActivity_id) 
       references Activity;

    alter table if exists Activity 
       add constraint FKcgslh3per1me24a9iov7ia53r 
       foreign key (topic_id) 
       references Topic;

    alter table if exists Person 
       add constraint FKhx6sbu85x6maywgxut2sxqb7m 
       foreign key (event_id) 
       references Event;

    alter table if exists Topic 
       add constraint FK7ako2w4aegodj0s8yawgswt5v 
       foreign key (event_id) 
       references Event;

    alter table if exists Topic 
       add constraint FK8kprmabtprwoof9nraefeol3c 
       foreign key (previousTopic_id) 
       references Topic;
insert into event (maxpersonallowed, name, planedenddatetime, planedstartdatetime, type) values (100,'Test Event','2022-11-11 13:23:44','2022-11-01 13:23:44','Test Type');
insert into person (comment, firstname, lastname, role, telephone,event_id) values ('No comment','Oliver','Sugic',1,'0123456789',1);
insert into person (comment, firstname, lastname, role, telephone,event_id) values ('No comment','Test ','Person',1,'0123456789',1);
insert into person (comment, firstname, lastname, role, telephone,event_id) values ('No comment','Person','Test',1,'0123456789',1);
insert into person (comment, firstname, lastname, role, telephone,event_id) values ('No comment','Firstname','Lastname',2,'0123456789',1);
insert into topic (comment, name, event_id) values ('NO comment X', 'Test Name', 1);
insert into topic (comment, name, event_id, previoustopic_id) values ('NO comment', 'Test Topic', 1, 1);
insert into activity(activityname, comment, ispublic, latitude, longitude, publicationdate, startdatetime,topic_id) values ('testactivity1','no comment',false,48.2685952973631, 14.25187750534175,current_date,'2008-11-11 13:23:44',1);
insert into activity(activityname, comment, ispublic, latitude, longitude, publicationdate, startdatetime,previousactivity_id,topic_id) values ('testactivity1','no comment',false,48.2685952973631, 14.25187750534175,current_date,'2008-11-11 13:23:44',1,1);
