= Konzept Excursion Guide / Schnitzeljagd

== Mögliche Namen

* excursion-guide
* tour-assistant

* Schnitzeljagd ... paper chase



== Ausgangssituation


Bei Reisen in Gruppen zB bei schulbezogenen Reiseveranstaltungen ist es wichtig, die Teilnehmer über Treffpunkte, Zustiegspunkte und ev. auch über Sehenswürdigkeiten zu informieren.

Dabei sollen diese detaillierten Informationen (GeoKoordinaten) erst sichtbar sein, wenn man sie braucht.

* Beispiel:
** Man besucht Mailand, Florenz und Pisa.
** Diese Stationen sind den Teilnehmern bekannt.
** Die Detailinformationen zB GeoKoordinaten werden erst bekannt gegeben, wenn man Sie braucht. Somit gibt es keine Verwechslungen und die Personen kommen nur zu den vereinbarten Punkten

* Es wird ev. eine Schnitzeljagd durchgeführt

== Problemstellung

* Die Weitergabe erfolgt oft ueber soziale Medien
** Diese Weitergabe erfolg unkontrolliert, nicht mehr gebrauchte Informationen sind weiter verfügbar und tragen ev. zur Verwirrung der Teilnehmer bei.


== Aufgabenstellung

=== Reiseleiter-App

* Eine Route kann geplant werden.
* Zu jedem Punkt der Route koennen jederzeit (Detail-)Informationen hinzugefuegt werden.
* Diese Detailinformationen werden ueber openstreetmap (osm) lokalisiert; es koennen Zusatzinformationen eingefuegt werden.
* Es gibt eine einen Creator- und einen User-Mode
** Routen werden im Creator-Modus erstellt
** Die Informationen koennen im User-Mode abgerufen werden.

* Werden die Infos vom User abgerufen, werden die Punkte in Google Maps oder osm angezeigt und es kann direkt dorthin geroutet werden
* Zum Abrufen der Informationen gibt es entweder eine Zeitsteuerung (eher nicht) oder der Reiseleiter / Creator kann die Information auf seiner App freigeben.

* Entscheidung MobileApp oder WebApp
** Ev. Creator-Mode in einer mobile App
** User-Mode in einer Web-App
*** Der Link zur User-Website ist per QR-Code verfuegbar

=== Schnitzeljagd-App

* Ev. knn auch in einer Stadt / einem Bereich eine Schnitzeljagd durchgefuehrt werden.

* https://www.mycityhunt.de/schnitzeljagd-in-der-stadt[Schnitzeljagd in der Stadt]


== Implementierung

* Angular
* Quarkus
* Android Jetpack Compose




